# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on: push
name: Slack Notification Demo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack 
    runs-on: ubuntu-latest
    steps:
    - name: Slack Noti
      uses: rtCamp/action-slack-notify@v2.0.1
      env:
        SLACK_WEBHOOK: ${{ secrets. SLACK_WEBHOOK_URL }}
